// <auto-generated />
using System;
using DeliveryCoreServer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeliveryCoreServer.Migrations
{
    [DbContext(typeof(VideoGameDBContext))]
    [Migration("20201211061655_publisherIdRequired3")]
    partial class publisherIdRequired3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DeliveryCoreServer.Models.Publishers", b =>
                {
                    b.Property<int>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("country");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("PublisherId")
                        .HasName("PK_publishers");

                    b.ToTable("publishers");
                });

            modelBuilder.Entity("DeliveryCoreServer.Models.VideoGames", b =>
                {
                    b.Property<int>("VideoGameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<int?>("PublisherId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("publisher_id");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.HasKey("VideoGameId")
                        .HasName("PK_videogames");

                    b.HasIndex("PublisherId");

                    b.ToTable("videogames");
                });

            modelBuilder.Entity("DeliveryCoreServer.Models.VideoGames", b =>
                {
                    b.HasOne("DeliveryCoreServer.Models.Publishers", "Publisher")
                        .WithMany("VideoGames")
                        .HasForeignKey("PublisherId")
                        .HasConstraintName("FK_videogames_publishers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("DeliveryCoreServer.Models.Publishers", b =>
                {
                    b.Navigation("VideoGames");
                });
#pragma warning restore 612, 618
        }
    }
}
